"""Official Python SDK for the ManyRows Server API."""

from manyrows.auth import bearer_token, verify_token, verify_token_async
from manyrows.bff import (
    AsyncBffClient,
    AsyncPublicProxy,
    BffClient,
    BffError,
    BffSession,
    ClientContext,
    OAuthCallbackHtml,
    OAuthCallbackOutcome,
    ProxyResponse,
    PublicProxy,
    dispatch_oauth_callback,
    dispatch_oauth_callback_async,
)
from manyrows.client import (
    AsyncClient,
    Client,
    ConfigItem,
    Delivery,
    DeliveryConfig,
    DeliveryFlags,
    FeatureFlag,
    ManyRowsError,
    Member,
    MembersResult,
    PermissionResult,
    User,
    UserField,
    UserFieldValue,
    UserResult,
)
from manyrows.secrets import SecretsError, compute_public_jwk_fingerprint, decrypt_secret
from manyrows.webhook import WebhookError, verify_webhook

__all__ = [
    "AsyncBffClient",
    "AsyncClient",
    "AsyncPublicProxy",
    "BffClient",
    "BffError",
    "BffSession",
    "Client",
    "ClientContext",
    "ConfigItem",
    "Delivery",
    "DeliveryConfig",
    "DeliveryFlags",
    "FeatureFlag",
    "ManyRowsError",
    "Member",
    "MembersResult",
    "OAuthCallbackHtml",
    "OAuthCallbackOutcome",
    "PermissionResult",
    "ProxyResponse",
    "PublicProxy",
    "SecretsError",
    "User",
    "UserField",
    "UserFieldValue",
    "UserResult",
    "WebhookError",
    "bearer_token",
    "compute_public_jwk_fingerprint",
    "decrypt_secret",
    "dispatch_oauth_callback",
    "dispatch_oauth_callback_async",
    "verify_token",
    "verify_token_async",
    "verify_webhook",
]

__version__ = "1.0.0"
